### ISSUE TITLE
Check possible bug in processing TrustlineUpdate

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#294]
Check if setting the `m_time `in `update_trustline` is the right thing to do, or a bug (https://github.com/trustlines-protocol/relay/blob/master/relay/network_graph/graph.py#L531). In a comment further down it says is represents the last modification time of the balance (https://github.com/trustlines-protocol/relay/blob/master/relay/network_graph/graph.py#L544).

**Comment by cducrest** [comment]
If you change the interest rates, you need to calculate the accrued interests and apply them, so you need to update the m_time.

More code-wise: 
This is called when receiving a `TrustlinesUpdate` event: https://github.com/trustlines-protocol/relay/blob/master/relay/relay.py#L717
This event is emitted here: https://github.com/trustlines-protocol/contracts/blob/master/contracts/CurrencyNetwork.sol#L1148
As you can see, a few line above we have `_applyInterests(_trustline)` which will update the m_time.

**Comment by berndbohmeier** [comment]
Yes, but I would argue like this:

if you change the interest rate, you need to calculate the accrued interests and apply them, so the balance will change. This should fire a `BalanceUpdate` event, and in reaction to that event the `m_time` needs to change. 
So there is no need to update `m_time` on `TrustlineUpdate` directly.

**Comment by berndbohmeier** [comment]
Yes, we should probably remove the edge if we close the trustline.

**Comment by cducrest** [comment]
We currently do not emit a `BalanceUpdate` event on changing credit limits even though the balance may be updated as far as I can tell.
We could change this in the contracts and then stop updating the m_time on the relay on `TrustlinesUpdate`. But I am not sure it makes it better, since every trustlines update on a trustlines with interest will then fire a `BalanceUpdate`.

**Comment by cducrest** [comment]
I would suggest we change the `TrustlinesUpdate` event to add the balance to it so that the user is aware of the new balance with the interest.
We handle this on the relay server by calling the `update_balance()` function if the balance changed.
There is no way for the relay to make the difference between a closed trustlines and a trustlines with 0 credit limits and balances, so I would just remove the edge from the graph when any of these cases occur within `update_trustline()`.

**Comment by cducrest** [comment]
(I just noticed your other issue, this works too, then we can remove the update of m_time on `update_trustline()` in the relay server, even though it does not really matter)

**Comment by berndbohmeier** [comment]
I would rather fix it by firing a BalanceUpdate, as for me that the Balance changes is just a side effect of the weird way that we handle the interests, so for my having a balance in TrustlineUpdate is really weird.

**Comment by cducrest** [comment]
Created task: https://github.com/trustlines-protocol/relay/issues/295

I cannot see how to know that a trustlines has been closed from the events though. When someone calls `closeTrustlineByTriangularTransfer`, we will receive a `TrustlineUpdate` event with (0,0,0,0). However, we do not know if the balance is 0 and if the edge in the graph must be removed unless we already processed the corresponding `BalanceUpdate` event. Same goes for the `BalanceUpdate` events.

If we do not handle events concurrently, we can try to remove the edge of the graph on both event, otherwise we might introduce a bug.

**Comment by berndbohmeier** [comment]
can you not trigger a check for all values to be zero at both events as last step?
So do all things, and if now all values are zero, remove the edge.

**Comment by berndbohmeier** [comment]
Ah I should finish reading you message first. We are using gevent, so we use some threading, but what you want to do should be fine. We can have a short chat about it.

**Comment by cducrest** [comment]
Tasks have been created, i believe this can be closed.
