### ISSUE TITLE
Check fields validation for bugs

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#304]
It looks suspicious, that `HexEncodedBytes` just assumes that it will receive a string and that 
`FeePayerField` does no validation at all. We should check that this works also if you provide a number for example.

**Comment by cducrest** [comment]
### HexEncodedBytes extraData

If we use `extraData = 12345678` we raise an error from the relay server: `marshmallow.exceptions.ValidationError: {'extraData': ['Could not parse hex-encoded bytes objects of attribute extraData: 12345678']}`.

I would say it is correct to reject this input on the relay server and only expect values that start with `0x` (as documented) but the error should be passed down to the clientlib.

Otherwise we can handle it by encoding the int to hex bytes, but it would bring confusion to the clientlib upon receiving the Transfer event extraData `0xbc614e` (encoded `12345678`). Lastly we can simply append `0x` when it is missing, but it could feel weird to some user expecting encoding from the relay.

### FeePayerField

If we use `feePayer = 1` in the clientlib, we get following error: `marshmallow.exceptions.ValidationError: {'feePayer': ['Not a valid string.']}`

If we use `feePayer = 'snedr` in the clientlib we get the following error: 
`marshmallow.exceptions.ValidationError: {'feePayer': ['Must be one of: sender, receiver.']}`

I believe it is expected to have errors for such inputs (as documented).

For all of these 3 errors, we see on the clientlib: ` Error: Error fetching http://localhost:5000/api/v1/networks/0xee35211C4D9126D520bBfeaf3cFee5FE7B86F221/path-info | Status 500 | Internal Server Error` which should be improved on the relay by using `abort(400, f"invalid parameter {parameter} with value {value}")` or something.

**Comment by cducrest** [comment]
This PR fixes the wrong return of error 500 instead of 422 from relay server: https://github.com/trustlines-protocol/relay/pull/309

**Comment by cducrest** [comment]
If you agree with the above @berndbohmeier, we can close this, else we can update the relay api to be more open.
