### ISSUE TITLE
Fix push notification endpoints

### ISSUE THREAD

**Issue by cducrest** [trustlines-protocol/relay#323]
Some endpoints related to push notifications are throwing an error on the relay server when push notifications are disabled.

We should disable the endpoint in this case.

**Comment by schmir-at-bb** [comment]
If firebase is not configured, these methods will do nothing: 
https://github.com/trustlines-protocol/relay/blob/master/relay/relay.py#L276-L289

From what I can tell this was done on purpose. I would just keep it that way.

The errors we've seen did only occur because push notifications had been **enabled** , see https://github.com/trustlines-network/deployment-config/issues/40 and the fix in https://github.com/trustlines-protocol/relay/pull/324

Therefore I'm closing this one, feel free to reopen if you still think we should change the current behaviour.

/cc @berndbohmeier
