### ISSUE TITLE
Check if a mypy upgrade or different config settings find more type errors

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#360]
In https://github.com/trustlines-protocol/relay/pull/354 we had a type error, which pycharm could catch, but mypy did not. Do some quick checks if we can make also mypy detect such errors.

**Comment by cducrest** [comment]
I introduced the error back : `def calculate_fees_for_meta_transaction() -> DelegationFees:` instead of `List[DelegationFees]` to try it out.

I upgraded to the most recent version of mypy `0.760` and no error was found. When I run `mypy --ignore-missing-imports --strict src/relay/blockchain/delegate.py`, I get many errors among which: `src/relay/blockchain/delegate.py:72: error: Returning Any from function declared to return "DelegationFees"`.

So it seems mypy is unable to find the return type in line 72: `return self.delegation_fees`. If we want to catch such "errors" we only need the option `--warn-return-any` which actually issues an error and not warning.

However this will also issue an error when the correct type is in the signature. To fix it we need to declare the type of `self.delegation_fees` in the constructor: `self.delegation_fees: List[DelegationFees] = delegation_fees`.

I personally don't think it makes sense to enforce this since I only want to use types if it makes it easier to autocomplete code when my editor knows the value is a NamedTuple for example (which it did).

**Comment by berndbohmeier** [comment]
We should not use `--warn-return-any`, as it is too strict I think.
The solution would be to declare the type in the constructor signature, not in the body.
```
def __init__(
        self,
        web3,
        node_address: str,
        identity_contract_abi,
        known_factories: List[str],
        delegation_fees: List[DelegationFees],
    ) -> None:
```

**Comment by berndbohmeier** [comment]
no need to update
