### ISSUE TITLE
Use marshmallows Schemas to properly define output scheme for api

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/relay#50]
At the moment we just format the output ourselves in the api. It is more clean to use schemas to define the output scheme.

**Comment by schmir** [comment]
I've done this for one function in 573b596e0927abd8a0ec109b03705a81757edc97.

The Trustline and TrustlineList resources use `.dump(...)` and then change the data to add additional fields. This is rather ugly, because we don't have a schema for the result of the function. We should `.dump` these results at the border, i.e. when the function exits.

**Comment by schmir** [comment]
more work has been done in 9a98135cb072580ecd3e6f4652f69343bb6b0379, with the the help of the marshmallow-oneofschema module.

**Comment by andfletcher** [comment]
Partially done / Good enough for now. Closing.
